### ISSUE TITLE
Allows the execution between learning and not learning 

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/SemCPS#1]
To include in the configuration file one boolean variable to execute the method with and without learning. To add the possibility to save the results of precision and recall in a file in both cases.

**Comment by omarrana** [comment]
Done I have updated the readme which shows how to add training enable and disable

The only change with training and no training weights are dynamically learned. 

https://github.com/i40-Tools/Alligator-PSL/blob/master/README.md

**Comment by igrangel** [comment]
It works based on the configuration. Still made some refactoring [here](https://github.com/i40-Tools/Alligator-PSL/commit/7a9cdf2ef96d40234f313a441c48760117792990). Could you please be more careful in the naming and formatting of the code?

**Comment by igrangel** [comment]
Can you please rename file1 [here](https://github.com/i40-Tools/Alligator-PSL/blob/7a9cdf2ef96d40234f313a441c48760117792990/src/main/java/pslApproach/DocumentAlignment.groovy#L210) and do not use this kind of names anymore? The variable names should have some semantic on it. 

In addition, please accommodate the predicate list one under the other, e.g., [here](https://github.com/i40-Tools/Alligator-PSL/blob/7a9cdf2ef96d40234f313a441c48760117792990/src/main/java/pslApproach/DocumentAlignment.groovy#L226). 

Further, every time you use a mathematical symbol, e.g., `+, =, ==,` etc, like [here](https://github.com/i40-Tools/Alligator-PSL/blob/7a9cdf2ef96d40234f313a441c48760117792990/src/main/java/pslApproach/DocumentAlignment.groovy#L253) provide a blank space before and after the symbol.
