### ISSUE TITLE
Influence of remove symmetric in results

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/SemCPS#11]
The [removeSymmetric](https://github.com/i40-Tools/Alligator-PSL/blob/01e59a6c862267cd2ccec0c943ffefd3373ea6e3/src/main/java/pslApproach/DocumentAlignment.groovy#L535) method is influencing the precision and recall results. 
If we manually change the value [here](https://github.com/i40-Tools/Alligator-PSL/blob/01e59a6c862267cd2ccec0c943ffefd3373ea6e3/src/main/java/pslApproach/DocumentAlignment.groovy#L582) setting `flag = 1` or `flag = 0` the results will vary dramatically.
Could you please check if PSL has a solution for this or maybe ask on the list? Is [this](https://github.com/i40-Tools/Alligator-PSL/blob/01e59a6c862267cd2ccec0c943ffefd3373ea6e3/src/main/java/pslApproach/DocumentAlignment.groovy#L325) configuration related?

**Comment by omarrana** [comment]
Hi
This is old code something is fishy. My push didn't got updated. I'm going to do again please recheck
________________________________

**Comment by omarrana** [comment]
Updated
