### ISSUE TITLE
compilng issue 

### ISSUE THREAD

**Issue by LIUHaohui** [i40-Tools/SemCPS#16]
hello 
during the compiling I still have problems of:
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The import org.apache.jena cannot be resolved
	The import org.apache.jena cannot be resolved
	The import com.hp cannot be resolved
	The import com.hp cannot be resolved
	The import com.hp cannot be resolved
	The import com.hp cannot be resolved
	The import com.hp cannot be resolved
	The import com.hp cannot be resolved
	The import com.hp cannot be resolved
	The import uni cannot be resolved
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	Model cannot be resolved to a type
	Krextor cannot be resolved to a type
	Krextor cannot be resolved to a type
	org.apache.jena cannot be resolved to a type
	RDFDataMgr cannot be resolved
	RDFDataMgr cannot be resolved
	RDFFormat cannot be resolved to a variable
	StmtIterator cannot be resolved to a type
	Model cannot be resolved to a type
	Statement cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	FileManager cannot be resolved
	Model cannot be resolved to a type
	ModelFactory cannot be resolved
	StmtIterator cannot be resolved to a type
	Statement cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	Resource cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	FileManager cannot be resolved
	Model cannot be resolved to a type
	ModelFactory cannot be resolved
	Model cannot be resolved to a type
	StmtIterator cannot be resolved to a type
	Model cannot be resolved to a type
	Cannot switch on a value of type String for source level below 1.7. Only convertible int values or enum variables are permitted
	Statement cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	StmtIterator cannot be resolved to a type
	Model cannot be resolved to a type
	RDFNode cannot be resolved to a type
	Statement cannot be resolved to a type
	RDFNode cannot be resolved to a type
	StmtIterator cannot be resolved to a type
	Model cannot be resolved to a type
	RDFNode cannot be resolved to a type
	Statement cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	RDFNode cannot be resolved to a type
	StmtIterator cannot be resolved to a type

	at main.Files2Facts.<init>(Files2Facts.java:16)
	at main.AlligatorMain.<init>(AlligatorMain.java:31)
	at main.AlligatorMain.main(AlligatorMain.java:36)
I was wondering if you have any advices on that?

**Comment by igrangel** [comment]
This is not an Issue, this is just that you are not importing correctly the Jena libraries. Please do it.
