### ISSUE TITLE
result issue

### ISSUE THREAD

**Issue by CaoHao1993** [i40-Tools/SemCPS#17]
I can run the AlligatorMain now. However, I test several sets of test amlfiles. 
The results are all showing like this:
INFERRING...
INFERENCE DONE
Accuracy:0.0
Error:0.0
True Positive:0
True Negative:0
False Positive:0
False Negative:0
Precision:1.0
Recall:1.0
Fmeasure:1.0

I wonder if  the results are right or not. I suppose it should have some difference.

**Comment by igrangel** [comment]
You are doing something wrong, results are wrong. Please check for the path in the configuration file.

**Comment by CaoHao1993** [comment]
INFERRING...
INFERENCE DONE
SIMILAR(aml1:Attribute5, aml2:Attribute4): 0.89
SIMILAR(aml1:ExternalReference2, aml2:ExternalReference2): 0.89
SIMILAR(aml2:ExternalReference1, aml1:ExternalReference1): 0.89
SIMILAR(aml2:InterfaceClass1, aml1:InterfaceClass1): 0.93
NOTSIMILAR(aml1:Attribute4, aml2:Attribute4): 1
NOTSIMILAR(aml2:ExternalReference2, aml1:ExternalReference1): 1
NOTSIMILAR(aml2:Attribute4, aml1:Attribute6): 1
NOTSIMILAR(aml2:ExternalReference1, aml1:ExternalReference2): 1
Accuracy:0.5
Error:4.0
True Positive:0
True Negative:4
False Positive:4
False Negative:0
Precision:0.0
Recall:1.0
Fmeasure:0.0


Answer like this is right?

**Comment by igrangel** [comment]
Yes, this is an example of a correct answer. Now you should include in the code what is explained here https://github.com/i40-Tools/SemCPS/issues/15 and close the issue if no more comments are in this regard.
