### ISSUE TITLE
To check the overall data conversion process to PSL

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/SemCPS#2]
When generating the RDF from AML and the PSL data, this should be in a directory that does not be overwritten in next generation. It can be also accumulative, but still not sure about this.

**Comment by omarrana** [comment]
fixed

https://github.com/i40-Tools/Alligator-PSL/blob/dfaeb77ef40e412264786bf81b1d56fad4a907d5/src/main/java/main/Files2Facts.java#L204-L208

**Comment by omarrana** [comment]
Fixed 
Just give path of AML heterogenity and folders will be created automatically.
Then you can add GoldStandard and training data.
To do this manually, you can create 
.../TestBed1/PSL/test/
.../TestBed1/PSL/train/
Folders will be created automatically if they are not there.
Example is in https://github.com/i40-Tools/Alligator-PSL/blob/master/README.md
updated readme
