### ISSUE TITLE
how can we integrate Alligator into Play framework?

### ISSUE THREAD

**Issue by LIUHaohui** [i40-Tools/SemCPS#20]
minor question, how can I use alligator when cooerating with Play framework?

**Comment by igrangel** [comment]
This is not a minor question and is something that should have been done more than two months ago.

**Comment by igrangel** [comment]
This is already DONE. You are supposed to improve it. If you clone [this](https://github.com/i40-Tools/AlligatorWorkbench) project you will have everything to run it. I have done it by myself and works perfectly with IntelligentIdea.
