### ISSUE TITLE
Writting proper comments

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/SemCPS#23]
Ideally, we should follow best practices to write comments (the description has not to be that long, but the parameters, as well as, the input and output should be as in the example) as described [here](http://www.oracle.com/technetwork/articles/java/index-137868.html). 

Format of a Doc Comment
A doc comment is written in HTML and must precede a class, field, constructor or method declaration. It is made up of two parts -- a description followed by block tags. In this example, the block tags are @param, @return, and @see.

/**
 Returns an Image object that can then be painted on the screen. 
 The url argument must specify an absolute {@link URL}. The name
 argument is a specifier that is relative to the url argument. 
 <p>
 This method always returns immediately, whether or not the 
 image exists. When this applet attempts to draw the image on
 the screen, the data will be loaded. The graphics primitives 
 that draw the image will incrementally paint on the screen. 
 
 @param  url  an absolute URL giving the base location of the image
 @param  name the location of the image, relative to the url argument
 @return      the image at the specified URL
 @see         Image
 */
```
 public Image getImage(URL url, String name) {
        try {
            return getImage(new URL(url, name));
        } catch (MalformedURLException e) {
            return null;
        }
 }
```

**Comment by omarrana** [comment]
This can be closed
