### ISSUE TITLE
Calculate and explain the meaning of Precision and Recall for the problem

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/SemCPS#3]
We have already the TP, FP, TN, FP, after checking they are correct computing precision and recall should not be a problem. Please try to get one example and run it until the end. Then, we can discuss further on top of this case you chose.

**Comment by omarrana** [comment]
Our computed Result

`

> aml2:InterfaceClass1	 aml1:InterfaceClass1                                                                                                 
> aml1:InterfaceClass1	 aml2:InterfaceClass1               
> aml1:Attribute5	 aml2:Attribute4                       
> aml2:Attribute4	 aml1:Attribute5                               
> 

`
Our GoldStandard

```

 aml2:InterfaceClass1	 aml1:InterfaceClass1                      
 aml1:InterfaceClass1	 aml2:InterfaceClass1                     
 aml1:Attribute5	 aml2:Attribute4                                  
 aml2:Attribute4	 aml1:Attribute5                            



```

Results are  which are correct in my opinion:                        

> `Accuracy:1.0     
> Error:0.0               
> Fmeasure:1.0                
> True negative:0              
> True Positive:4                
> False Positive:4               
> False Negative:0                   
> Precision (Positive):1.0                  
> Recall: (Positive)1.0                    
> Precision:(Negative)1.0                     
> Recall:(Negative)1.0                    
> 

`                         
But lets modify the Gold Standard and make some values false.                        

> `aml2:InterfaceClass1	 aml1:InterfaceClass2 // changed                  
> aml1:InterfaceClass1	 aml2:InterfaceClass3 // changed                      
> aml1:Attribute5	 aml2:Attribute4                        
> aml2:Attribute4	 aml1:Attribute5                      
> 

`                                
Results are  which is also correct:                        

> `Accuracy:0.5                          
> Error:2.0                         
> Fmeasure:0.6666666666666666                        
> True negative:0                          
> True Positive:2                          
> False Positive:2                     
> False Negative:2                        
> Precision (Positive):0.5                         
> Recall: (Positive)1.0                          
> Precision:(Negative)1.0                      
> Recall:(Negative)0.0                        
> 

`          
Now i want to have value for True Negative  So i modify GoldStandard by removing one value              

> `aml2:InterfaceClass1	 aml1:InterfaceClass2                     
> aml1:InterfaceClass1	 aml2:InterfaceClass3                     
> **aml1:Attribute5	 aml2:Attribute4// correct value removed**                    
> aml2:Attribute4	 aml1:Attribute5                       
> 

`
Result is : I think True negative should be one here                                

> `Accuracy:0.3333333333333333                              
> Error:2.0                       
> Fmeasure:0.5                              
> True negative:0                            
> True Positive:1                              
> False Positive:1                          
> False Negative:2                          
> Precision (Positive):0.3333333333333333                      
> Recall: (Positive)1.0                           
> Precision:(Negative)1.0                         
> Recall:(Negative)0.0                         
> 

`
What do you think, Am i on the wrong page?

**Comment by igrangel** [comment]
There were some typos, please check again after [this](https://github.com/i40-Tools/Alligator-PSL/commit/b2b1bc897ba464fb3c803003e9b7df7177e76730) commit.

**Comment by omarrana** [comment]
I have updated the code and now precision and recall works.
So now we can also include non-similar values.
So similar.txt can have values with 1 or 0.
Also in the Gold Standard.
Now we can get true negative and false negative.
This can be closed now
