### ISSUE TITLE
Refactor conversion method by having standards as parameters

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/SemCPS#4]
This [method](https://github.com/i40-Tools/Alligator-PSL/blob/01369c93e6e6e68300b8feb768242cac4ef7549b/src/main/java/main/Files2Facts.java#L224) has to be refactored. You are mixing things there. The standard which we are dealing need to be passed as a parameter. You are making things to tailored to OPC UA and AML. Of course our focus now is make this working but we have to do it well.

**Comment by omarrana** [comment]
fixed

https://github.com/i40-Tools/Alligator-PSL/blob/dfaeb77ef40e412264786bf81b1d56fad4a907d5/src/main/java/main/Files2Facts.java#L204-L208

**Comment by igrangel** [comment]
It is ok, still, there are general things that should not be located inside the specific standard, i.e., aml code. 
Check https://github.com/i40-Tools/Alligator-PSL/blob/77c0aab6bafcfd9efecc59e667822569406d4fba/src/main/java/main/Files2Facts.java#L205-209
