### ISSUE TITLE
Refactoring InitFileWriters method by correctly reading the file directory

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/SemCPS#5]
[This](https://github.com/i40-Tools/Alligator-PSL/blob/fd67befff660068e39f27746407523226f45993a/src/main/java/main/Files2Facts.java#L531) is a dangerous programming example, as well as the lines that follow. This is totally not scalable and we must think in our solution to be scalable. Therefore, you have to read the directory that you have configured in [this](https://github.com/i40-Tools/Alligator-PSL/blob/fd67befff660068e39f27746407523226f45993a/src/main/java/main/Files2Facts.java#L525) way. I agree that the first thing is to make things work, but right after that we have to think in make our application to be scalable. Similarly, you have to do this with the names of the method. If needed, we can used the semantic described in the ontology but what we can't do is to tailored our solution with this level of specification.

**Comment by omarrana** [comment]
fixed made A generic List
https://github.com/i40-Tools/Alligator-PSL/blob/dfaeb77ef40e412264786bf81b1d56fad4a907d5/src/main/java/main/Files2Facts.java#L239-L275

**Comment by igrangel** [comment]
Please check [here](https://github.com/i40-Tools/Alligator-PSL/commit/32f4e2f2e1349da7c82a3615d2d71c9a95d83d6f)
